FROM node:20-alpine AS build

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build --configuration=production

FROM nginx:stable-alpine

COPY --from=build /app/dist/angular-app /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
