# Generated by Django 6.0.3 on 2026-03-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="created_by",
        ),
    ]
