/*
 * Simple OpenAI API helpers.
 * NOTE: Calling the OpenAI API directly from client-side code exposes your API key to users.
 * This file is intentionally written in plain JS for clarity, but consider using a server proxy
 * for production. See comments below.
 */

/** Build headers for OpenAI requests */
function buildHeaders(apiKey) {
  return {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer ' + apiKey
  };
}

/** Send chat messages to OpenAI chat completions endpoint.
 * messages: array of { role, content }
 * model: string model id
 * apiKey: user's API key (string)
 */
/**
 * Send chat messages to OpenAI chat completions endpoint.
 * - model: string
 * - messages: [{ role, content }, ...]
 * - apiKey: string
 * - maxResponseTokens: number (limits tokens generated by the model)
 */
export async function sendChat(model, messages, apiKey, maxResponseTokens = 512) {
  // Some newer models expect `max_completion_tokens` instead of `max_tokens`.
  // Use `max_completion_tokens` to limit generated tokens for compatibility.
  const body = { model, messages, max_completion_tokens: maxResponseTokens };
  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: buildHeaders(apiKey),
    body: JSON.stringify(body)
  });
  if (!res.ok) {
    // try to extract a concise error message from JSON body
    let msg = res.statusText;
    try {
      const j = await res.json();
      if (j && j.error && j.error.message) msg = j.error.message;
      else if (j && j.message) msg = j.message;
    } catch (e) {
      // ignore parse errors
    }
    throw new Error(msg || 'OpenAI chat request failed');
  }

  const data = await res.json();
  const text = (data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content) || '';
  return text;
}

/** Request image generation using the dedicated image model.
 * Returns a data URL (image/png;base64,...)
 */
export async function generateImage(prompt, apiKey, size = '1024x1024') {
  const body = { model: 'gpt-image-1-mini', prompt, size };
  const res = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: buildHeaders(apiKey),
    body: JSON.stringify(body)
  });
  if (!res.ok) {
    let msg = res.statusText;
    try {
      const j = await res.json();
      if (j && j.error && j.error.message) msg = j.error.message;
      else if (j && j.message) msg = j.message;
    } catch (e) {}
    throw new Error(msg || 'OpenAI image request failed');
  }

  const data = await res.json();
  const b64 = data.data && data.data[0] && data.data[0].b64_json;
  if (!b64) throw new Error('No image returned');
  return 'data:image/png;base64,' + b64;
}

/*
 * Reminder: Exposing the API key in client code is insecure. Prefer a small server
 * that stores the key and proxies requests. This frontend-only approach is useful
 * for quick demos or personal projects where you are aware of the risk.
 */
